from py_jwt_validator import PyJwtValidator, PyJwtException
import requests

jwt = 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImIyZWQwZGIxZjY2MWQ4OTg5OTY5YmFiNzhkMmZhZTc1NjRmZGMzYTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI2NDMwMTc1NTgyOTAtcjRrc2FtajE3b3BudWc5Z2t0bDNmdm11MzFwZzdiMnAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI2NDMwMTc1NTgyOTAtcjRrc2FtajE3b3BudWc5Z2t0bDNmdm11MzFwZzdiMnAuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTEzOTU3MTU3MjM3NTE4OTI0MzkiLCJlbWFpbCI6Imx6ci5hZHJpYW4xOTk1QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiSUVnNjdDMk81UHQyeC1kbUZMRmZwQSIsIm5vbmNlIjoibm9uY2UiLCJpYXQiOjE1ODAzMTIwMjAsImV4cCI6MTU4MDMxNTYyMH0.Id7DIqv00BXTpzF4M7WR4JSRNyqCD6sNEW69EP2CXqNoIN2CIVPtm-4cebreimP4DTKt50i6-NKfcss6O9-aYd9QdXEfN8LfbYkb1ICVngN671-Q2LTBKSgbbbWl03MtNFSXOPPoMj1nNw40Mnsv5WlyIbem9r0gbm68-leFibtRsGMqxA_8htnHWD1e1Hps5euE0z9xcZd2OxQab0gPyFcIG5htT8O2WuZEZJMj2yzQvlf4xDHE6sBhHDHEATTxdf-APlQKQQvQIqOz344N7YKIIBwCspLhM-QOAOaUqIkG-2bgzQlDyZ_ymQxrKGOgdnm-Cva_jEhd3W77ZriUEA'
try:
    print(PyJwtValidator(jwt, auto_verify=False, check_expiry=False).verify(True))
except PyJwtException as e:
    print(f"Exception caught. Error: {e}")